### ISSUE TITLE
jekyll 3.8.5 | Error:  File exists @ dir_s_mkdir  jekyll/_site/tag/inspire

### ISSUE THREAD

**Issue by Hakem22** [jekyll/jekyll-paginate#41]
I am using `jekyll 3.8.5` and `jekyll-paginate (1.1.0)`
when I run my docker-compose I get this error:
`jekyll 3.8.5 | Error: File exists @ dir_s_mkdir jekyll/_site/tag/inspire 
`My _config.yml
```
plugins:
  - jekyll-paginate

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -...
paginate: 5
paginate_path: "/news/page:num/"
```
Anyone have an idea about how to fix that, I am new with jekyll.
Thank you.
